/*
 * globals.c: definition and handling of the set of global variables
 *            of the library
 *
 * The bottom of this file is automatically generated by build_glob.py
 * based on the description file global.data
 *
 * See Copyright for the status of this software.
 *
 * Gary Pennington <Gary.Pennington@uk.sun.com>
 * daniel@veillard.com
 */

#define IN_LIBXML
#include "libxml.h"

#include <stdlib.h>
#include <string.h>

#include "libxml/globals.h"
#include "libxml/xmlmemory.h"
#include "libxml/threads.h"

#include "private/error.h"
#include "private/globals.h"
#include "private/threads.h"
#include "private/tree.h"

/* #define DEBUG_GLOBALS */

/*
 * Helpful Macro
 */
#ifdef LIBXML_THREAD_ENABLED
#define IS_MAIN_THREAD (nl_xmlIsMainThread())
#else
#define IS_MAIN_THREAD 1
#endif

/*
 * Mutex to protect "ForNewThreads" variables
 */
static xmlMutex xmlThrDefMutex;

/**
 * nl_xmlInitGlobals:
 *
 * DEPRECATED: Alias for nl_xmlInitParser.
 */
void nl_xmlInitGlobals(void) {
    nl_xmlInitParser();
}

/**
 * xmlInitGlobalsInternal:
 *
 * Additional initialisation for multi-threading
 */
void xmlInitGlobalsInternal(void) {
    xmlInitMutex(&xmlThrDefMutex);
}

/************************************************************************
 *									*
 *	All the user accessible global variables of the library		*
 *									*
 ************************************************************************/

/*
 * Memory allocation routines
 */
#undef	nl_xmlFree
#undef	nl_xmlMalloc
#undef	nl_xmlMallocAtomic
#undef	nl_xmlMemStrdup
#undef	nl_xmlRealloc

#if defined(DEBUG_MEMORY_LOCATION) || defined(DEBUG_MEMORY)
xmlFreeFunc nl_xmlFree = (xmlFreeFunc) xmlMemFree;
xmlMallocFunc nl_xmlMalloc = (xmlMallocFunc) xmlMemMalloc;
xmlMallocFunc nl_xmlMallocAtomic = (xmlMallocFunc) xmlMemMalloc;
xmlReallocFunc nl_xmlRealloc = (xmlReallocFunc) xmlMemRealloc;
xmlStrdupFunc nl_xmlMemStrdup = (xmlStrdupFunc) xmlMemoryStrdup;
#else
/**
 * nl_xmlFree:
 * @mem: an already allocated block of memory
 *
 * The variable holding the libxml free() implementation
 */
xmlFreeFunc nl_xmlFree = free;
/**
 * nl_xmlMalloc:
 * @size:  the size requested in bytes
 *
 * The variable holding the libxml malloc() implementation
 *
 * Returns a pointer to the newly allocated block or NULL in case of error
 */
xmlMallocFunc nl_xmlMalloc = malloc;
/**
 * nl_xmlMallocAtomic:
 * @size:  the size requested in bytes
 *
 * The variable holding the libxml malloc() implementation for atomic
 * data (i.e. blocks not containing pointers), useful when using a
 * garbage collecting allocator.
 *
 * Returns a pointer to the newly allocated block or NULL in case of error
 */
xmlMallocFunc nl_xmlMallocAtomic = malloc;
/**
 * nl_xmlRealloc:
 * @mem: an already allocated block of memory
 * @size:  the new size requested in bytes
 *
 * The variable holding the libxml realloc() implementation
 *
 * Returns a pointer to the newly reallocated block or NULL in case of error
 */
xmlReallocFunc nl_xmlRealloc = realloc;
/**
 * xmlPosixStrdup
 * @cur:  the input char *
 *
 * a strdup implementation with a type signature matching POSIX
 *
 * Returns a new xmlChar * or NULL
 */
static char *
xmlPosixStrdup(const char *cur) {
    return((char*) nl_xmlCharStrdup(cur));
}
/**
 * nl_xmlMemStrdup:
 * @str: a zero terminated string
 *
 * The variable holding the libxml strdup() implementation
 *
 * Returns the copy of the string or NULL in case of error
 */
xmlStrdupFunc nl_xmlMemStrdup = xmlPosixStrdup;
#endif /* DEBUG_MEMORY_LOCATION || DEBUG_MEMORY */

#include "libxml/threads.h"
#include "libxml/globals.h"
// #include "libxml/SAX.h"

#undef	htmlDefaultSAXHandler
#undef	nl_oldXMLWDcompatibility
#undef	nl_xmlBufferAllocScheme
#undef	nl_xmlDefaultBufferSize
#undef	xmlDefaultSAXHandler
#undef	nl_xmlDefaultSAXLocator
#undef	nl_xmlDoValidityCheckingDefaultValue
#undef	nl_xmlGenericError
#undef	nl_xmlStructuredError
#undef	nl_xmlGenericErrorContext
#undef	nl_xmlStructuredErrorContext
#undef	nl_xmlGetWarningsDefaultValue
#undef	nl_xmlIndentTreeOutput
#undef  nl_xmlTreeIndentString
#undef	nl_xmlKeepBlanksDefaultValue
#undef	nl_xmlLineNumbersDefaultValue
#undef	nl_xmlLoadExtDtdDefaultValue
#undef	nl_xmlParserDebugEntities
#undef	nl_xmlParserVersion
#undef	nl_xmlPedanticParserDefaultValue
#undef	nl_xmlSaveNoEmptyTags
#undef	nl_xmlSubstituteEntitiesDefaultValue
#undef	nl_xmlRegisterNodeDefaultValue
#undef	nl_xmlDeregisterNodeDefaultValue
#undef	nl_xmlLastError

#undef  nl_xmlParserInputBufferCreateFilenameValue
#undef  nl_xmlOutputBufferCreateFilenameValue
/**
 * nl_xmlParserVersion:
 *
 * Constant string describing the internal version of the library
 */
const char *nl_xmlParserVersion = LIBXML_VERSION_STRING LIBXML_VERSION_EXTRA;

/**
 * nl_xmlBufferAllocScheme:
 *
 * DEPRECATED: Don't use.
 *
 * Global setting, default allocation policy for buffers, default is
 * XML_BUFFER_ALLOC_EXACT
 */
xmlBufferAllocationScheme nl_xmlBufferAllocScheme = XML_BUFFER_ALLOC_EXACT;
static xmlBufferAllocationScheme xmlBufferAllocSchemeThrDef = XML_BUFFER_ALLOC_EXACT;
/**
 * nl_xmlDefaultBufferSize:
 *
 * DEPRECATED: Don't use.
 *
 * Global setting, default buffer size. Default value is BASE_BUFFER_SIZE
 */
int nl_xmlDefaultBufferSize = BASE_BUFFER_SIZE;
static int xmlDefaultBufferSizeThrDef = BASE_BUFFER_SIZE;

/*
 * Parser defaults
 */

/**
 * nl_oldXMLWDcompatibility:
 *
 * Global setting, DEPRECATED.
 */
int nl_oldXMLWDcompatibility = 0; /* DEPRECATED */
/**
 * nl_xmlParserDebugEntities:
 *
 * DEPRECATED: Don't use
 *
 * Global setting, asking the parser to print out debugging information.
 * while handling entities.
 * Disabled by default
 */
int nl_xmlParserDebugEntities = 0;
static int xmlParserDebugEntitiesThrDef = 0;
/**
 * nl_xmlDoValidityCheckingDefaultValue:
 *
 * DEPRECATED: Use the modern options API with XML_PARSE_DTDVALID.
 *
 * Global setting, indicate that the parser should work in validating mode.
 * Disabled by default.
 */
int nl_xmlDoValidityCheckingDefaultValue = 0;
static int xmlDoValidityCheckingDefaultValueThrDef = 0;
/**
 * nl_xmlGetWarningsDefaultValue:
 *
 * DEPRECATED: Don't use
 *
 * Global setting, indicate that the DTD validation should provide warnings.
 * Activated by default.
 */
int nl_xmlGetWarningsDefaultValue = 1;
static int xmlGetWarningsDefaultValueThrDef = 1;
/**
 * nl_xmlLoadExtDtdDefaultValue:
 *
 * DEPRECATED: Use the modern options API with XML_PARSE_DTDLOAD.
 *
 * Global setting, indicate that the parser should load DTD while not
 * validating.
 * Disabled by default.
 */
int nl_xmlLoadExtDtdDefaultValue = 0;
static int xmlLoadExtDtdDefaultValueThrDef = 0;
/**
 * nl_xmlPedanticParserDefaultValue:
 *
 * DEPRECATED: Use the modern options API with XML_PARSE_PEDANTIC.
 *
 * Global setting, indicate that the parser be pedantic
 * Disabled by default.
 */
int nl_xmlPedanticParserDefaultValue = 0;
static int xmlPedanticParserDefaultValueThrDef = 0;
/**
 * nl_xmlLineNumbersDefaultValue:
 *
 * DEPRECATED: The modern options API always enables line numbers.
 *
 * Global setting, indicate that the parser should store the line number
 * in the content field of elements in the DOM tree.
 * Disabled by default since this may not be safe for old classes of
 * application.
 */
int nl_xmlLineNumbersDefaultValue = 0;
static int xmlLineNumbersDefaultValueThrDef = 0;
/**
 * nl_xmlKeepBlanksDefaultValue:
 *
 * DEPRECATED: Use the modern options API with XML_PARSE_NOBLANKS.
 *
 * Global setting, indicate that the parser should keep all blanks
 * nodes found in the content
 * Activated by default, this is actually needed to have the parser
 * conformant to the XML Recommendation, however the option is kept
 * for some applications since this was libxml1 default behaviour.
 */
int nl_xmlKeepBlanksDefaultValue = 1;
static int xmlKeepBlanksDefaultValueThrDef = 1;
/**
 * nl_xmlSubstituteEntitiesDefaultValue:
 *
 * DEPRECATED: Use the modern options API with XML_PARSE_NOENT.
 *
 * Global setting, indicate that the parser should not generate entity
 * references but replace them with the actual content of the entity
 * Disabled by default, this should be activated when using XPath since
 * the XPath data model requires entities replacement and the XPath
 * engine does not handle entities references transparently.
 */
int nl_xmlSubstituteEntitiesDefaultValue = 0;
static int xmlSubstituteEntitiesDefaultValueThrDef = 0;

/**
 * nl_xmlRegisterNodeDefaultValue:
 *
 * DEPRECATED: Don't use
 */
xmlRegisterNodeFunc nl_xmlRegisterNodeDefaultValue = NULL;
static xmlRegisterNodeFunc xmlRegisterNodeDefaultValueThrDef = NULL;

/**
 * nl_xmlDeregisterNodeDefaultValue:
 *
 * DEPRECATED: Don't use
 */
xmlDeregisterNodeFunc nl_xmlDeregisterNodeDefaultValue = NULL;
static xmlDeregisterNodeFunc xmlDeregisterNodeDefaultValueThrDef = NULL;

/**
 * nl_xmlParserInputBufferCreateFilenameValue:
 *
 * DEPRECATED: Don't use
 */
xmlParserInputBufferCreateFilenameFunc nl_xmlParserInputBufferCreateFilenameValue = NULL;
static xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameValueThrDef = NULL;

/**
 * nl_xmlOutputBufferCreateFilenameValue:
 *
 * DEPRECATED: Don't use
 */
xmlOutputBufferCreateFilenameFunc nl_xmlOutputBufferCreateFilenameValue = NULL;
static xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameValueThrDef = NULL;

/**
 * nl_xmlGenericError:
 *
 * Global setting: function used for generic error callbacks
 */
xmlGenericErrorFunc nl_xmlGenericError = nl_xmlGenericErrorDefaultFunc;
static xmlGenericErrorFunc xmlGenericErrorThrDef = nl_xmlGenericErrorDefaultFunc;
/**
 * nl_xmlStructuredError:
 *
 * Global setting: function used for structured error callbacks
 */
xmlStructuredErrorFunc nl_xmlStructuredError = NULL;
static xmlStructuredErrorFunc xmlStructuredErrorThrDef = NULL;
/**
 * nl_xmlGenericErrorContext:
 *
 * Global setting passed to generic error callbacks
 */
void *nl_xmlGenericErrorContext = NULL;
static void *xmlGenericErrorContextThrDef = NULL;
/**
 * nl_xmlStructuredErrorContext:
 *
 * Global setting passed to structured error callbacks
 */
void *nl_xmlStructuredErrorContext = NULL;
static void *xmlStructuredErrorContextThrDef = NULL;
xmlError nl_xmlLastError;

/*
 * output defaults
 */
/**
 * nl_xmlIndentTreeOutput:
 *
 * Global setting, asking the serializer to indent the output tree by default
 * Enabled by default
 */
int nl_xmlIndentTreeOutput = 1;
static int xmlIndentTreeOutputThrDef = 1;

/**
 * nl_xmlTreeIndentString:
 *
 * The string used to do one-level indent. By default is equal to "  " (two spaces)
 */
const char *nl_xmlTreeIndentString = "  ";
static const char *xmlTreeIndentStringThrDef = "  ";

/**
 * nl_xmlSaveNoEmptyTags:
 *
 * Global setting, asking the serializer to not output empty tags
 * as <empty/> but <empty></empty>. those two forms are indistinguishable
 * once parsed.
 * Disabled by default
 */
int nl_xmlSaveNoEmptyTags = 0;
static int xmlSaveNoEmptyTagsThrDef = 0;

#ifdef LIBXML_SAX1_ENABLED
/**
 * xmlDefaultSAXHandler:
 *
 * DEPRECATED: This handler is unused and will be removed from future
 * versions.
 *
 * Default SAX version1 handler for XML, builds the DOM tree
 */
xmlSAXHandlerV1 xmlDefaultSAXHandler = {
    xmlSAX2InternalSubset,
    xmlSAX2IsStandalone,
    xmlSAX2HasInternalSubset,
    xmlSAX2HasExternalSubset,
    xmlSAX2ResolveEntity,
    xmlSAX2GetEntity,
    xmlSAX2EntityDecl,
    xmlSAX2NotationDecl,
    xmlSAX2AttributeDecl,
    xmlSAX2ElementDecl,
    xmlSAX2UnparsedEntityDecl,
    xmlSAX2SetDocumentLocator,
    xmlSAX2StartDocument,
    xmlSAX2EndDocument,
    xmlSAX2StartElement,
    xmlSAX2EndElement,
    xmlSAX2Reference,
    xmlSAX2Characters,
    xmlSAX2Characters,
    xmlSAX2ProcessingInstruction,
    xmlSAX2Comment,
    xmlParserWarning,
    xmlParserError,
    xmlParserError,
    xmlSAX2GetParameterEntity,
    xmlSAX2CDataBlock,
    xmlSAX2ExternalSubset,
    1,
};
#endif /* LIBXML_SAX1_ENABLED */

/**
 * nl_xmlDefaultSAXLocator:
 *
 * DEPRECATED: Don't use
 *
 * The default SAX Locator
 * { getPublicId, getSystemId, getLineNumber, getColumnNumber}
 */
xmlSAXLocator nl_xmlDefaultSAXLocator = {
    nl_xmlSAX2GetPublicId,
    nl_xmlSAX2GetSystemId,
    nl_xmlSAX2GetLineNumber,
    nl_xmlSAX2GetColumnNumber
};

#if defined(LIBXML_HTML_ENABLED) && defined(LIBXML_SAX1_ENABLED)
/**
 * htmlDefaultSAXHandler:
 *
 * DEPRECATED: This handler is unused and will be removed from future
 * versions.
 *
 * Default old SAX v1 handler for HTML, builds the DOM tree
 */
xmlSAXHandlerV1 htmlDefaultSAXHandler = {
    xmlSAX2InternalSubset,
    NULL,
    NULL,
    NULL,
    NULL,
    xmlSAX2GetEntity,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    xmlSAX2SetDocumentLocator,
    xmlSAX2StartDocument,
    xmlSAX2EndDocument,
    xmlSAX2StartElement,
    xmlSAX2EndElement,
    NULL,
    xmlSAX2Characters,
    xmlSAX2IgnorableWhitespace,
    xmlSAX2ProcessingInstruction,
    xmlSAX2Comment,
    xmlParserWarning,
    xmlParserError,
    xmlParserError,
    NULL,
    xmlSAX2CDataBlock,
    NULL,
    1,
};
#endif /* LIBXML_HTML_ENABLED */

/**
 * nl_xmlInitializeGlobalState:
 * @gs: a pointer to a newly allocated global state
 *
 * nl_xmlInitializeGlobalState() initialize a global state with all the
 * default values of the library.
 */
void
nl_xmlInitializeGlobalState(xmlGlobalStatePtr gs)
{
#ifdef DEBUG_GLOBALS
    fprintf(stderr, "Initializing globals at %p for thread %d\n",
	    (void *) gs, nl_xmlGetThreadId());
#endif

    nl_xmlMutexLock(&xmlThrDefMutex);

#if defined(LIBXML_HTML_ENABLED) && defined(LIBXML_LEGACY_ENABLED) && defined(LIBXML_SAX1_ENABLED)
    inithtmlDefaultSAXHandler(&gs->htmlDefaultSAXHandler);
#endif

    gs->nl_oldXMLWDcompatibility = 0;
    gs->nl_xmlBufferAllocScheme = xmlBufferAllocSchemeThrDef;
    gs->nl_xmlDefaultBufferSize = xmlDefaultBufferSizeThrDef;
#if defined(LIBXML_SAX1_ENABLED) && defined(LIBXML_LEGACY_ENABLED)
    initxmlDefaultSAXHandler(&gs->xmlDefaultSAXHandler, 1);
#endif /* LIBXML_SAX1_ENABLED */
    gs->nl_xmlDefaultSAXLocator.getPublicId = nl_xmlSAX2GetPublicId;
    gs->nl_xmlDefaultSAXLocator.getSystemId = nl_xmlSAX2GetSystemId;
    gs->nl_xmlDefaultSAXLocator.getLineNumber = nl_xmlSAX2GetLineNumber;
    gs->nl_xmlDefaultSAXLocator.getColumnNumber = nl_xmlSAX2GetColumnNumber;
    gs->nl_xmlDoValidityCheckingDefaultValue =
         xmlDoValidityCheckingDefaultValueThrDef;
#if defined(DEBUG_MEMORY_LOCATION) | defined(DEBUG_MEMORY)
    gs->nl_xmlFree = (xmlFreeFunc) xmlMemFree;
    gs->nl_xmlMalloc = (xmlMallocFunc) xmlMemMalloc;
    gs->nl_xmlMallocAtomic = (xmlMallocFunc) xmlMemMalloc;
    gs->nl_xmlRealloc = (xmlReallocFunc) xmlMemRealloc;
    gs->nl_xmlMemStrdup = (xmlStrdupFunc) xmlMemoryStrdup;
#else
    gs->nl_xmlFree = (xmlFreeFunc) free;
    gs->nl_xmlMalloc = (xmlMallocFunc) malloc;
    gs->nl_xmlMallocAtomic = (xmlMallocFunc) malloc;
    gs->nl_xmlRealloc = (xmlReallocFunc) realloc;
    gs->nl_xmlMemStrdup = (xmlStrdupFunc) nl_xmlStrdup;
#endif
    gs->nl_xmlGetWarningsDefaultValue = xmlGetWarningsDefaultValueThrDef;
    gs->nl_xmlIndentTreeOutput = xmlIndentTreeOutputThrDef;
    gs->nl_xmlTreeIndentString = xmlTreeIndentStringThrDef;
    gs->nl_xmlKeepBlanksDefaultValue = xmlKeepBlanksDefaultValueThrDef;
    gs->nl_xmlLineNumbersDefaultValue = xmlLineNumbersDefaultValueThrDef;
    gs->nl_xmlLoadExtDtdDefaultValue = xmlLoadExtDtdDefaultValueThrDef;
    gs->nl_xmlParserDebugEntities = xmlParserDebugEntitiesThrDef;
    gs->nl_xmlParserVersion = LIBXML_VERSION_STRING;
    gs->nl_xmlPedanticParserDefaultValue = xmlPedanticParserDefaultValueThrDef;
    gs->nl_xmlSaveNoEmptyTags = xmlSaveNoEmptyTagsThrDef;
    gs->nl_xmlSubstituteEntitiesDefaultValue =
        xmlSubstituteEntitiesDefaultValueThrDef;

    gs->nl_xmlGenericError = xmlGenericErrorThrDef;
    gs->nl_xmlStructuredError = xmlStructuredErrorThrDef;
    gs->nl_xmlGenericErrorContext = xmlGenericErrorContextThrDef;
    gs->nl_xmlStructuredErrorContext = xmlStructuredErrorContextThrDef;
    gs->nl_xmlRegisterNodeDefaultValue = xmlRegisterNodeDefaultValueThrDef;
    gs->nl_xmlDeregisterNodeDefaultValue = xmlDeregisterNodeDefaultValueThrDef;

	gs->nl_xmlParserInputBufferCreateFilenameValue = xmlParserInputBufferCreateFilenameValueThrDef;
	gs->nl_xmlOutputBufferCreateFilenameValue = xmlOutputBufferCreateFilenameValueThrDef;
    memset(&gs->nl_xmlLastError, 0, sizeof(xmlError));

    nl_xmlMutexUnlock(&xmlThrDefMutex);
}

/**
 * nl_xmlCleanupGlobals:
 *
 * DEPRECATED: This function is a no-op. Call xmlCleanupParser
 * to free global state but see the warnings there. xmlCleanupParser
 * should be only called once at program exit. In most cases, you don't
 * have call cleanup functions at all.
 */
void nl_xmlCleanupGlobals(void) {
}

/**
 * xmlCleanupGlobalsInternal:
 *
 * Additional cleanup for multi-threading
 */
void xmlCleanupGlobalsInternal(void) {
    nl_xmlResetError(&nl_xmlLastError);

    xmlCleanupMutex(&xmlThrDefMutex);
    __xmlGlobalInitMutexDestroy();
}

void
nl_xmlThrDefSetGenericErrorFunc(void *ctx, xmlGenericErrorFunc handler) {
    nl_xmlMutexLock(&xmlThrDefMutex);
    xmlGenericErrorContextThrDef = ctx;
    if (handler != NULL)
	xmlGenericErrorThrDef = handler;
    else
	xmlGenericErrorThrDef = nl_xmlGenericErrorDefaultFunc;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
}

void
nl_xmlThrDefSetStructuredErrorFunc(void *ctx, xmlStructuredErrorFunc handler) {
    nl_xmlMutexLock(&xmlThrDefMutex);
    xmlStructuredErrorContextThrDef = ctx;
    xmlStructuredErrorThrDef = handler;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
}

/**
 * nl_xmlRegisterNodeDefault:
 * @func: function pointer to the new RegisterNodeFunc
 *
 * Registers a callback for node creation
 *
 * Returns the old value of the registration function
 */
xmlRegisterNodeFunc
nl_xmlRegisterNodeDefault(xmlRegisterNodeFunc func)
{
    xmlRegisterNodeFunc old = nl_xmlRegisterNodeDefaultValue;

    __xmlRegisterCallbacks = 1;
    nl_xmlRegisterNodeDefaultValue = func;
    return(old);
}

xmlRegisterNodeFunc
nl_xmlThrDefRegisterNodeDefault(xmlRegisterNodeFunc func)
{
    xmlRegisterNodeFunc old;

    nl_xmlMutexLock(&xmlThrDefMutex);
    old = xmlRegisterNodeDefaultValueThrDef;

    __xmlRegisterCallbacks = 1;
    xmlRegisterNodeDefaultValueThrDef = func;
    nl_xmlMutexUnlock(&xmlThrDefMutex);

    return(old);
}

/**
 * nl_xmlDeregisterNodeDefault:
 * @func: function pointer to the new DeregisterNodeFunc
 *
 * Registers a callback for node destruction
 *
 * Returns the previous value of the deregistration function
 */
xmlDeregisterNodeFunc
nl_xmlDeregisterNodeDefault(xmlDeregisterNodeFunc func)
{
    xmlDeregisterNodeFunc old = nl_xmlDeregisterNodeDefaultValue;

    __xmlRegisterCallbacks = 1;
    nl_xmlDeregisterNodeDefaultValue = func;
    return(old);
}

xmlDeregisterNodeFunc
nl_xmlThrDefDeregisterNodeDefault(xmlDeregisterNodeFunc func)
{
    xmlDeregisterNodeFunc old;

    nl_xmlMutexLock(&xmlThrDefMutex);
    old = xmlDeregisterNodeDefaultValueThrDef;

    __xmlRegisterCallbacks = 1;
    xmlDeregisterNodeDefaultValueThrDef = func;
    nl_xmlMutexUnlock(&xmlThrDefMutex);

    return(old);
}

#if defined(LIBXML_HTML_ENABLED) && defined(LIBXML_SAX1_ENABLED)
#undef	htmlDefaultSAXHandler
xmlSAXHandlerV1 *
__htmlDefaultSAXHandler(void) {
    if (IS_MAIN_THREAD)
	return (&htmlDefaultSAXHandler);
    else
	return (&nl_xmlGetGlobalState()->htmlDefaultSAXHandler);
}
#endif

#undef nl_xmlLastError
xmlError *
__nl_xmlLastError(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlLastError);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlLastError);
}

/*
 * The following memory routines were apparently lost at some point,
 * and were re-inserted at this point on June 10, 2004.  Hope it's
 * the right place for them :-)
 */
#if defined(LIBXML_THREAD_ALLOC_ENABLED) && defined(LIBXML_THREAD_ENABLED)
#undef nl_xmlMalloc
xmlMallocFunc *
__xmlMalloc(void){
    if (IS_MAIN_THREAD)
        return (&nl_xmlMalloc);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlMalloc);
}

#undef nl_xmlMallocAtomic
xmlMallocFunc *
__xmlMallocAtomic(void){
    if (IS_MAIN_THREAD)
        return (&nl_xmlMallocAtomic);
    else
        return (&nl_xmlGetGlobalState()->nl_xmlMallocAtomic);
}

#undef nl_xmlRealloc
xmlReallocFunc *
__xmlRealloc(void){
    if (IS_MAIN_THREAD)
        return (&nl_xmlRealloc);
    else
        return (&nl_xmlGetGlobalState()->nl_xmlRealloc);
}

#undef nl_xmlFree
xmlFreeFunc *
__xmlFree(void){
    if (IS_MAIN_THREAD)
        return (&nl_xmlFree);
    else
        return (&nl_xmlGetGlobalState()->nl_xmlFree);
}

xmlStrdupFunc *
__xmlMemStrdup(void){
    if (IS_MAIN_THREAD)
        return (&nl_xmlMemStrdup);
    else
        return (&nl_xmlGetGlobalState()->nl_xmlMemStrdup);
}

#endif

/*
 * Everything starting from the line below is
 * Automatically generated by build_glob.py.
 * Do not modify the previous line.
 */


#undef	nl_oldXMLWDcompatibility
int *
__nl_oldXMLWDcompatibility(void) {
    if (IS_MAIN_THREAD)
	return (&nl_oldXMLWDcompatibility);
    else
	return (&nl_xmlGetGlobalState()->nl_oldXMLWDcompatibility);
}

#undef	nl_xmlBufferAllocScheme
xmlBufferAllocationScheme *
__nl_xmlBufferAllocScheme(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlBufferAllocScheme);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlBufferAllocScheme);
}
xmlBufferAllocationScheme nl_xmlThrDefBufferAllocScheme(xmlBufferAllocationScheme v) {
    xmlBufferAllocationScheme ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlBufferAllocSchemeThrDef;
    xmlBufferAllocSchemeThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlDefaultBufferSize
int *
__nl_xmlDefaultBufferSize(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlDefaultBufferSize);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlDefaultBufferSize);
}
int nl_xmlThrDefDefaultBufferSize(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlDefaultBufferSizeThrDef;
    xmlDefaultBufferSizeThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#ifdef LIBXML_SAX1_ENABLED
#undef	xmlDefaultSAXHandler
xmlSAXHandlerV1 *
__xmlDefaultSAXHandler(void) {
    if (IS_MAIN_THREAD)
	return (&xmlDefaultSAXHandler);
    else
	return (&nl_xmlGetGlobalState()->xmlDefaultSAXHandler);
}
#endif /* LIBXML_SAX1_ENABLED */

#undef	nl_xmlDefaultSAXLocator
xmlSAXLocator *
__nl_xmlDefaultSAXLocator(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlDefaultSAXLocator);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlDefaultSAXLocator);
}

#undef	nl_xmlDoValidityCheckingDefaultValue
int *
__nl_xmlDoValidityCheckingDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlDoValidityCheckingDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlDoValidityCheckingDefaultValue);
}
int nl_xmlThrDefDoValidityCheckingDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlDoValidityCheckingDefaultValueThrDef;
    xmlDoValidityCheckingDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlGenericError
xmlGenericErrorFunc *
__nl_xmlGenericError(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlGenericError);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlGenericError);
}

#undef	nl_xmlStructuredError
xmlStructuredErrorFunc *
__nl_xmlStructuredError(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlStructuredError);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlStructuredError);
}

#undef	nl_xmlGenericErrorContext
void * *
__nl_xmlGenericErrorContext(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlGenericErrorContext);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlGenericErrorContext);
}

#undef	nl_xmlStructuredErrorContext
void * *
__nl_xmlStructuredErrorContext(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlStructuredErrorContext);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlStructuredErrorContext);
}

#undef	nl_xmlGetWarningsDefaultValue
int *
__nl_xmlGetWarningsDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlGetWarningsDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlGetWarningsDefaultValue);
}
int nl_xmlThrDefGetWarningsDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlGetWarningsDefaultValueThrDef;
    xmlGetWarningsDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlIndentTreeOutput
int *
__nl_xmlIndentTreeOutput(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlIndentTreeOutput);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlIndentTreeOutput);
}
int nl_xmlThrDefIndentTreeOutput(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlIndentTreeOutputThrDef;
    xmlIndentTreeOutputThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlTreeIndentString
const char * *
__nl_xmlTreeIndentString(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlTreeIndentString);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlTreeIndentString);
}
const char * nl_xmlThrDefTreeIndentString(const char * v) {
    const char * ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlTreeIndentStringThrDef;
    xmlTreeIndentStringThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlKeepBlanksDefaultValue
int *
__nl_xmlKeepBlanksDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlKeepBlanksDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlKeepBlanksDefaultValue);
}
int nl_xmlThrDefKeepBlanksDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlKeepBlanksDefaultValueThrDef;
    xmlKeepBlanksDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlLineNumbersDefaultValue
int *
__nl_xmlLineNumbersDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlLineNumbersDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlLineNumbersDefaultValue);
}
int nl_xmlThrDefLineNumbersDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlLineNumbersDefaultValueThrDef;
    xmlLineNumbersDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlLoadExtDtdDefaultValue
int *
__nl_xmlLoadExtDtdDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlLoadExtDtdDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlLoadExtDtdDefaultValue);
}
int nl_xmlThrDefLoadExtDtdDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlLoadExtDtdDefaultValueThrDef;
    xmlLoadExtDtdDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlParserDebugEntities
int *
__nl_xmlParserDebugEntities(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlParserDebugEntities);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlParserDebugEntities);
}
int nl_xmlThrDefParserDebugEntities(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlParserDebugEntitiesThrDef;
    xmlParserDebugEntitiesThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlParserVersion
const char * *
__nl_xmlParserVersion(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlParserVersion);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlParserVersion);
}

#undef	nl_xmlPedanticParserDefaultValue
int *
__nl_xmlPedanticParserDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlPedanticParserDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlPedanticParserDefaultValue);
}
int nl_xmlThrDefPedanticParserDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlPedanticParserDefaultValueThrDef;
    xmlPedanticParserDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlSaveNoEmptyTags
int *
__nl_xmlSaveNoEmptyTags(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlSaveNoEmptyTags);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlSaveNoEmptyTags);
}
int nl_xmlThrDefSaveNoEmptyTags(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlSaveNoEmptyTagsThrDef;
    xmlSaveNoEmptyTagsThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlSubstituteEntitiesDefaultValue
int *
__nl_xmlSubstituteEntitiesDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlSubstituteEntitiesDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlSubstituteEntitiesDefaultValue);
}
int nl_xmlThrDefSubstituteEntitiesDefaultValue(int v) {
    int ret;
    nl_xmlMutexLock(&xmlThrDefMutex);
    ret = xmlSubstituteEntitiesDefaultValueThrDef;
    xmlSubstituteEntitiesDefaultValueThrDef = v;
    nl_xmlMutexUnlock(&xmlThrDefMutex);
    return ret;
}

#undef	nl_xmlRegisterNodeDefaultValue
xmlRegisterNodeFunc *
__nl_xmlRegisterNodeDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlRegisterNodeDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlRegisterNodeDefaultValue);
}

#undef	nl_xmlDeregisterNodeDefaultValue
xmlDeregisterNodeFunc *
__nl_xmlDeregisterNodeDefaultValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlDeregisterNodeDefaultValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlDeregisterNodeDefaultValue);
}

#undef	nl_xmlParserInputBufferCreateFilenameValue
xmlParserInputBufferCreateFilenameFunc *
__nl_xmlParserInputBufferCreateFilenameValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlParserInputBufferCreateFilenameValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlParserInputBufferCreateFilenameValue);
}

#undef	nl_xmlOutputBufferCreateFilenameValue
xmlOutputBufferCreateFilenameFunc *
__nl_xmlOutputBufferCreateFilenameValue(void) {
    if (IS_MAIN_THREAD)
	return (&nl_xmlOutputBufferCreateFilenameValue);
    else
	return (&nl_xmlGetGlobalState()->nl_xmlOutputBufferCreateFilenameValue);
}

